# Site settings
title: "Erik Gaius Capistrano | Resume"
description: "Erik Gaius Capistrano's Resume as a Software Developer."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Erik Gaius L. Capistrano"
resume_title:                   "Full Stack Developer"
resume_contact_email:
  "gaius.coffee@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide (Experience is not shown
# because it is the only required section)
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/gaiuscoffee"
  resume_twitter_url:           "http://twitter.com/gaiuscoffee"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "http://facebook.com/gaiuscoffee"
  resume_linkedin_url:          "https://www.linkedin.com/in/gaiuscoffee"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://gaius.coffee"

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _congif.yml are only recognized when the server starts